[package]
name = "game"
version = "0.1.0"
authors = ["William Lundstedt <bananavice@gmail.com>"]

[dependencies]
failure = "0.1.1"
png = "*"
serde="*"
serde_derive = "*"
bincode="*"
embla = { path = "./embla/" }
